In [1]:
import pandas as pd # Data Frame
import numpy as np # Number Array
import matplotlib.pyplot as plt
import mglearn

In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("iris_dataset의 키: {}".format(iris_dataset.keys()))

iris_dataset의 키: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [3]:
print(iris_dataset['DESCR'][:193] + "\n...")

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [4]:
print("타깃의 이름: {}".format(iris_dataset['target_names']))

타깃의 이름: ['setosa' 'versicolor' 'virginica']


In [5]:
print("특성의 이름: {}".format(iris_dataset['feature_names']))

특성의 이름: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print("data의 크기: {}".format(iris_dataset['data'].shape))

data의 크기: (150, 4)


In [7]:
print("data의 처음 다섯 행:\n{}".format(iris_dataset['data'][:5]))

data의 처음 다섯 행:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
print("target의 크기: {}".format(iris_dataset['target'].shape))


target의 크기: (150,)


In [9]:
print("타깃:\n{}".format(iris_dataset['target']))

타깃:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state = 0)

In [11]:
print("X_train의 크기: {}".format(X_train.shape))
print("Y_train의 크기: {}".format(Y_train.shape))

X_train의 크기: (112, 4)
Y_train의 크기: (112,)


In [12]:
print("X_test의 크기: {}".format(X_test.shape))
print("Y_test의 크기: {}".format(Y_test.shape))

X_test의 크기: (38, 4)
Y_test의 크기: (38,)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [29]:
knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [30]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [31]:
prediction = knn.predict(X_new)
print("예측 : {}".format(prediction))
print("예측한 타깃의 이름: {}".format(iris_dataset['target_names'][prediction]))

예측 : [0]
예측한 타깃의 이름: ['setosa']


In [32]:
Y_pred =  knn.predict(X_test)
print("테스트 세트에 대한 예측값:\n {}".format(Y_pred))
print("테스트 세트에 대한 정답값:\n {}".format(Y_test))

테스트 세트에 대한 예측값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트 세트에 대한 정답값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [33]:
print("테스트 세트의 정확도: {:.2f}".format(np.mean(Y_pred == Y_test)))

테스트 세트의 정확도: 0.97


In [34]:
print("훈련 세트의 정확도: {:.3f}".format(knn.score(X_train, Y_train)))
print("테스트 세트의 정확도: {:.3f}".format(knn.score(X_test, Y_test)))

훈련 세트의 정확도: 0.964
테스트 세트의 정확도: 0.974
